name: configure-aws-credentials-with-tags
description: Assumes roles in AWS that have useful role session tags
runs:
  using: node12
  main: action/dist/index.js
inputs:
  api-url:
    description: The URL of the API that vends credentials
    required: true
  role-arn:
    description: The full ARN of the role you want to assume
    required: true
  audience:
    description: Value to pass to Github to use for the JWT audience
    required: true
